/* Automatic generated by './build/bin/build-entry.js' */

import Grad4 from './grad-4/index.js';

const components = [
    Grad4
];

const install = function(Vue, opts = {}) {
    if (Vue.prototype.$isServer) return;
    components.map(component => {
        if (component.props && component.props.hasOwnProperty('themes')) {
            component.props.themes.default = () => {
                return opts
            }
        }
        Vue.component(component.name, component);
        console.log("-------",component.name);
    });
};

export default {
    version: '1.0.0',
    install,
    Grad4
};